### ISSUE TITLE
Enforce typing

### ISSUE THREAD

**Issue by morgangiraud** [mortendahl/tf-encrypted#101]
We want to enforce typing in Circle-ci. 

To do so, we need to invest the necessary time to make the codebase fully typed. Since this work is fairly invasive, It can happen in multiple pull request to avoid too much code conflict.

The Makefile already contains the `typecheck` command. When the work is done the `typecheck` command should be added to the `test` command

**Comment by bendecoste** [comment]
can we start w/ file by file like we did for linting in the beginning?

**Comment by morgangiraud** [comment]
To do it file by file, one would need to fake all missing type with `Any` and then, on a regular basis, tighten the typing.

I would argue that one would be better off by actually doing the work in one pass or at least a maximum of it to make the command pass.

**Comment by ianlivingstone** [comment]
> I would argue that one would be better off by actually doing the work in one pass or at least a maximum of it to make the command pass.

This makes sense to me, how much work would this be?

**Comment by morgangiraud** [comment]
the command `make typecheck` returns a certain amount of errors but not too much. And most of the possible typing use case can have an example in the existing codebase.

Unless typing reveals a bad design which completely blocks the typing I would say, someone, can do it in 2 full days focused on it.

**Comment by justin1121** [comment]
I feel like this is pretty blocked until we figure out how to type the memoize decorator or mypy improves. See this issue with some discussion about decorators and types: https://github.com/python/mypy/issues/3157. TL;DR : types with decorators don't seem to be very well supported.

**Comment by ianlivingstone** [comment]
Thoughts on above @morgangiraud ? If you agree with @justin1121 lets move this into blocked and we can return to it once we have a work around.

**Comment by ianlivingstone** [comment]
Moving into blocked until we have some clarity on the above!

**Comment by morgangiraud** [comment]
> types with decorators don't seem to be very well supported.
Indeed, we have no choice here, either we contribute to `mypy` or we don't use decorators. But since decorators have already made their way into the codebase, I guess we're stuck with them.

I guess, the only thing we can do for now, is enforce typing as much as we can and then use `# type: ignore` on lines that can't be understood by `mypy`.

One thing to note: typing needs `python3.6` and @mortendahl already found out that `python3.5` is much more accessible on Linux distro. We probably need a `python3.5` solution to be more accessible.

**Comment by ianlivingstone** [comment]
> One thing to note: typing needs python3.6 and @mortendahl already found out that python3.5 is much more accessible on Linux distro. We probably need a python3.5 solution to be more accessible and automatize the process to get it.

Given the discussion in https://github.com/mortendahl/tf-encrypted/issues/167 and https://github.com/mortendahl/tf-encrypted/pull/173, it sounds like we need to drop some typing support to properly support 3.5 unless we can get `strip-hints` to work unless we want to commit to only supporting 3.6 (and just wait for the Linux distros to update to 3.6 or advise using conda or virtualenv). 

If that's true, where do we want to land on this divide? What's best for our productivity without making tf-encrypted inaccessible or less accessible to researchers and data scientists?

cc @morgangiraud @mortendahl @bendecoste @justin1121 @jvmancuso @yanndupis

**Comment by mortendahl** [comment]
my vote is on supporting python3.5, tell `mypy` to ignore decorators, and use the old typing syntax for variables if we have to. but just to make sure: what are the limitations of `mypy` and decorators?

**Comment by justin1121** [comment]
Some examples here: https://github.com/python/mypy/issues/3157. I can't remember all of the problems I was having with `mypy` and decorators but I spent a couple hours trying to get it to work. The big one is a combination of problems with args and kwargs which we're using in the memoize function. I could not get `mypy` to correctly figure out what the types of the args kwargs were. Using `Any` might work but I think I was having problems with that as  well.

**Comment by mortendahl** [comment]
thanks! is it possible to not type decorators altogether, or will `mypy` complain?

**Comment by jvmancuso** [comment]
>it sounds like we need to drop some typing support to properly support 3.5 unless we can get strip-hints to work unless we want to commit to only supporting 3.6 (and just wait for the Linux distros to update to 3.6 or advise using conda or virtualenv).
maybe it's reasonable to assume people will be using conda or venv already?  from my experience, anybody in data science/ML whose at all Python-savvy would use a package/environment manager that could handle different versions of Python.  I think it's reasonable to add a few lines of code to the installation process instead of reworking type hints for the entire repository, especially since we already recommend using a package manager like this in the README and since people should be using 3.6+ for future projects anyway.  the larger question is do we expect people to be integrating TFE into existing projects that use python 3.5?  if that's the issue, I think we have a bigger problem since places like Google have massive 2.7 codebases that'll be a monster to migrate from and that we don't plan on supporting 2.7

if this is more of a question of what devops/engineering people would prefer, then I'm a bit less certain about all this 😄

**Comment by mortendahl** [comment]
@jvmancuso they could in principle generate the graph using python3, export the pb file, and reload in whatever they want after that -- don't know if they would jump through that hoop though

**Comment by mortendahl** [comment]
also, are we sure it's just a question of running `strip-hints` as part of installation? i got the impression that it'll have to be used at runtime instead, to essential strip the files on-the-fly, but quite possibly wrong on this!

**Comment by morgangiraud** [comment]
> (and just wait for the Linux distros to update to 3.6 or advise using conda or virtualenv)

Just to note about the timeline: After a quick look, the next debian version having python3.6 by default will land in March 2019.

About `strip-hints`, the doc says `The processed code is written to stdout` so we can dump every files without types with a good command line normally (unless `strip-hints` breaks our code of course).

**Comment by ianlivingstone** [comment]
Based on our discussion yesterday, we've decided to adopt Python 3.5 as the repository standard. As such, we can only use the hinting syntax supported by 3.5. 

Given the above, is there any work left here for mypy? Does it have a Python 3.5 support mode?

**Comment by morgangiraud** [comment]
Yes, there are:
- Missing stubs for TF functions 
- Missing function types in tf-encrypted
- It would be great to decrease the amount of `Any` types too. Those kill the value of types.

**Comment by mortendahl** [comment]
Closing since we've ended up with a more limited use of typing
