### ISSUE TITLE
Tag first release candidate of tf-encrypted

### ISSUE THREAD

**Issue by ianlivingstone** [mortendahl/tf-encrypted#118]
Once we've cleaned out our old releases and tags off github, docker hub, and other artifact repositories we can tag our first ever release candidate of tf-encrypted.

The first official version will be `0.1.0` to properly follow PEP 440 and the major.minor.bug schema which is detailed in the [RELEASING.md](./RELEASING.md) document in this repository.

**Comment by mortendahl** [comment]
think clearing is done!

**Comment by ianlivingstone** [comment]
Done! https://pypi.org/project/tf-encrypted/0.1.0/
