### ISSUE TITLE
conv2d weight gradient bug

### ISSUE THREAD

**Issue by koenvanderveen** [mortendahl/tf-encrypted#150]
In the conv2d_backward branch, I am working on computing the gradients of the weights of the conv layer. My test does not pass, as the values in the Pond weight gradient tensor are not in the correct position. The values themselves are correct, but the positions in the tensor are not. I created a separate test for the im2col function, which seems to be working correctly. I have been trying to get this right for a while now, but  it seems like I am missing something obvious. The relevant code is in tests/test_convolution.py and tensorflow_encrypted/tensor/int100.py in the _conv2d_bw function in the conv2d_backward branch. Help would be appreciated

**Comment by mortendahl** [comment]
@jvmancuso you might be just the right guy here! :)

**Comment by koenvanderveen** [comment]
solved by #156
