### ISSUE TITLE
Multiply a PondPrivateTensor and a scalar from the left

### ISSUE THREAD

**Issue by morgangiraud** [mortendahl/tf-encrypted#152]
Today we can do:
`out = xp * 1.`

But we can't do:
`out = 1. * xp`

**Comment by mortendahl** [comment]
been wanting this for a long time -- any ideas how it could work in Python?

**Comment by morgangiraud** [comment]
It's done here : https://github.com/mortendahl/tf-encrypted/pull/151/files#diff-3d2500094f8c483b442294291a8eacc4R797 👍
