### ISSUE TITLE
Securenn select share should work correctly for any pond tensor type

### ISSUE THREAD

**Issue by justin1121** [mortendahl/tf-encrypted#161]
Currently, the select share protocol can take in any pond tensor but it returns a private pond tensor. We should be returning the same type of pond tensor passed in.

Another issue is that to take full advantage of the pond protocol and so that select share is generic to any pond tensor type we need to not mask with zero directly in the protocols. The zero masking should be added just before sending to P2 instead.

**Comment by ianlivingstone** [comment]
Is this a bug or a feature?

**Comment by bendecoste** [comment]
could probably label it either or.  The masking problem is just deleting an addition, and it's a pretty trivial protocol so fixing this will be easy.

**Comment by bendecoste** [comment]
The masking problem is also covered in #159

**Comment by bendecoste** [comment]
This has been fixed.
