### ISSUE TITLE
PyPi support for Python 3.5

### ISSUE THREAD

**Issue by mortendahl** [mortendahl/tf-encrypted#167]
Python 3.5 is what currently comes with Debian 9 (which is popular on GCP and Raspberry Pi), and it's messy to install 3.6. At the same time the only reason we don't currently support 3.5 seems to be the type hints, so maybe something as simple as [`strip-hints`](https://pypi.org/project/strip-hints/) could be used to build a 3.5 compatible PyPi package?

cc @ianlivingstone @morgangiraud any thoughts?

**Comment by ianlivingstone** [comment]
Should be relatively easy to setup, will need to make `setup.py` dynamic and add a few steps into the Makefile.

See https://stackoverflow.com/questions/40114100/uploading-different-versions-python-2-7-vs-3-5-to-pypi for more information.

**Comment by morgangiraud** [comment]
@mortendahl Totally agree with what you said. As @ianlivingstone said, with tests running on both versions I think we are fine.
