### ISSUE TITLE
Make the API closer to TF

### ISSUE THREAD

**Issue by morgangiraud** [mortendahl/tf-encrypted#175]
We want to have an improved API for TFE. The goal is to be as close as possible to TF, so people don't have to learn another API on top of TF.

More precisely this issue focus on transforming the [TFE logistic regression example](https://github.com/mortendahl/tf-encrypted/blob/master/examples/logreg/tfe-logreg.py) so it looks the same as the [TF example](https://github.com/mortendahl/tf-encrypted/blob/master/examples/logreg/tf-logreg.py).

This include:
- [x] Add `reduce_sum` alias
- [x] Add `matmul` alias
- [x] Add a default LocalConfig that will be used by a protocol (Add a warning)
- [x] Add a new sessions system
- [x] Add a default protocol that will be used by default when calling operations (tfe.matmul ...)
- [x] Allows `define_private_input`to be used as an annotation

**Comment by mortendahl** [comment]
some ideas in https://github.com/mortendahl/tf-encrypted/issues/149 as well

**Comment by mortendahl** [comment]
> Allows define_private_input to accept a TF.Tensor directly (add a warning for security implication)

My main concern here is that it's ignoring the main difference between TF and TFE: that in TFE it's important who knows which values. However, if the warning is big enough then maybe this is okay as a way of quickly prototyping stuff. See also #149 though for ideas on how to make the InputProvider interface simpler to work with, although it doesn't remove the need for some computations to be moved under a function.

Another issue that's not clear here is how we'll mix in numpy (used eg by keras datasets), as that's a popular way of loading/preprocessing data. In the mnist demo for instance, I had to manually convert the simple keras data loading into something that works directly with tf.tensors.

> Allows define_private_variable to accept a shape and a random algo name directly to avoid importing TensorFlow

Makes a lot of sense! We need to make it clear whether the initial value is public or private but that's a minor detail.

> Add a default LocalConfig that will be used by a protocol (Add a warning)

Like it! We can even allow people to specify it up front with eg `tfe.set_config()` to also make it easier to use remote configs

> Add a default protocol that will be used by default when calling operations (tfe.matmul ...)

Yes!
