### ISSUE TITLE
SecureNN with any backing tensor

### ISSUE THREAD

**Issue by justin1121** [mortendahl/tf-encrypted#202]
When the initial SecureNN MVP as described here (https://github.com/mortendahl/tf-encrypted/issues/106) is completed we want to expand on this and make it so it can work with any backing tensor (e.g. `Int32Tensor` and `Int64Tensor`). The initial MVP will be finished with only CRT support. 

### Next Steps

- [x] share convert (should be completed as part as MVP)
- [x] add proper support for encoding numbers to fixed point representations inside the int32 and int64 tensors
- [ ] test secure with int32 and int64 tensors

**Comment by mortendahl** [comment]
skipping int32 support for now (although nothing should prevent it from working)
