### ISSUE TITLE
Easy deployment to AWS/GCP

### ISSUE THREAD

**Issue by mortendahl** [mortendahl/tf-encrypted#22]
Make it easy to quickly get up and running on AWS or GCP. Could take the form of documentation or code (perhaps along [these lines](https://github.com/mortendahl/privateml/tree/master/tensorflow/spdz/configs/gcp))

**Comment by ianlivingstone** [comment]
Prepackaged configs for kubernetes might be a good way to get this deployed now that they both support k8s as a service.
