### ISSUE TITLE
Input syntax

### ISSUE THREAD

**Issue by mortendahl** [mortendahl/tf-encrypted#240]
@bendecoste raised a comment the other day that our way of specifying which player runs which function differs from TF, eg
```python
def load_data():
    ...

x = tfe.private_input(load_data, 'prediction-client')
```
or 
```python
@tfe.private_input('prediction-client')
def load_data():
    ...

x = load_data()
```

Is it worth instead being able to do
```python
def load_data():
    ...

with tfe.player('prediction-client'):
    x = load_data()
```
to match closer with the `tf.device()` syntax? (could even be `tfe.device` but might not capture the same thing)

**Comment by jvmancuso** [comment]
I personally think context managers and decorators are both great to have -- context manager is a bit more general if you don't want to define the code as a specific function, but the decorator is less cumbersome in cases where you do.  I imagine the first block is also useful, as it's a bit more intuitive at first glance.

**Comment by mortendahl** [comment]
Closing, seems to have been fixed along the way
