### ISSUE TITLE
Bug in network B and C 

### ISSUE THREAD

**Issue by yanndupis** [mortendahl/tf-encrypted#248]
[Network A](https://github.com/mortendahl/tf-encrypted/blob/master/examples/securenn/network_a.py) works perfectly fine since we are using the exact `ReLU` with `securenn` and improved the tfe api. However we still get a very bad accuracy for [network b](https://github.com/mortendahl/tf-encrypted/blob/master/examples/securenn/network_b.py) and [c](https://github.com/mortendahl/tf-encrypted/blob/master/examples/securenn/network_c.py). We are aware that we have a bug with the exact `ReLU` that needs to be fixed. However, not sure it's the cause of the bad accuracy. When I used the `.pb` file approach for network c last week, I was getting a good accuracy on the mnist set.

**Comment by ianlivingstone** [comment]
Does this block anything we need for the launch @yanndupis ?

**Comment by yanndupis** [comment]
I don't think it does. As an example we will show network a. Thanks.

**Comment by ianlivingstone** [comment]
Did we track down the bug?

**Comment by yanndupis** [comment]
The bug hasn't been tracked. Let's come back to it once `securenn + int64 + exact relu` is completed.

**Comment by mortendahl** [comment]
@yanndupis can this be closed?

**Comment by ianlivingstone** [comment]
cc @yanndupis ^

**Comment by yanndupis** [comment]
I will check this week if with the securenn protocol completed now it's working.

**Comment by mortendahl** [comment]
any updates @yanndupis?

**Comment by yanndupis** [comment]
We found the bugs in for this issue. There were missing relus, and we were using channel last during training for the convolution and pooling layers however we were using channel first for secure inference. Once the PR #375 is merged we can close this issue.
