### ISSUE TITLE
Setup linting

### ISSUE THREAD

**Issue by ianlivingstone** [mortendahl/tf-encrypted#25]
We should add a linter to the code base so our code is conformant!

**Comment by morgangiraud** [comment]
If I'm not mistaken, @justin1121 @bendecoste and me are using `pycodestyle` with default settings.

If anybody as anything to say against this linter. Let's keep this one. We can move to a more complex setup later on.

**Comment by bendecoste** [comment]
Works for me

**Comment by bendecoste** [comment]
We should probably run a linter as part of CI.
