### ISSUE TITLE
Load a pretrained model for prediction

### ISSUE THREAD

**Issue by ianlivingstone** [mortendahl/tf-encrypted#26]
Details to come

**Comment by justin1121** [comment]
Right now I'm working through a vgg16 model from keras exported as a tensorflow model where the weights and everything are frozen directly into the protobuf graph. This contains a lot of ops we'll need to begin so its a good place to start experimenting with how these ops will work in MPC land. 

Right now I'm just reading the graph and redoing the ops directly in normal tensorflow. Once I get this all sorted I'll look into making this work in mpc land!
