### ISSUE TITLE
Install tensorflow via conda instead of pip

### ISSUE THREAD

**Issue by ianlivingstone** [mortendahl/tf-encrypted#264]
Inside our container we're installing tensorflow cpu using pip. However, a recent article pointed out that if you install tf via pip you don't get the cpu optimized version suggesting that you should install tensorflow directly via conda.

Let's try to modify our container to use conda to install tensorflow instead of via pip and see if it leads to any improvement in our environment.

Article: https://towardsdatascience.com/stop-installing-tensorflow-using-pip-for-performance-sake-5854f9d9eb0c

**Comment by ianlivingstone** [comment]
In order to use conda, we need to package up the int64 build of tensorflow into a conda package. 

Once we have that, we can revisit establishing a conda build.

**Comment by ianlivingstone** [comment]
FYI @yanndupis ^

**Comment by justin1121** [comment]
We've come to find out that int32 and int64 matmuls aren't supported MKL and that's why the above article is suggesting installing via conda. So going to close this issue because doing this will hurt us not help us!
