### ISSUE TITLE
Add development setup instructions

### ISSUE THREAD

**Issue by ianlivingstone** [mortendahl/tf-encrypted#290]
Today, we don't have good instructions on how to get set up with a development environment for tf-encrypted.

**Comment by ianlivingstone** [comment]
We should also take the time to expand upon our external install instructions as well (including how to install using conda).

**Comment by justin1121** [comment]
Custom ops building for upcoming secure random PR:

Assuming python/anaconda and tf-encrypted has been bootstrapped.

Ubuntu

```
sudo apt install libtool automake g++
make build
```

Note: Other linux dist should work similar to this

MacOS

Assuming brew is installed.

```
brew install libtool automake
```

@mortendahl anything to add here?
