### ISSUE TITLE
Replace all tf.Print with tf.print

### ISSUE THREAD

**Issue by mortendahl** [mortendahl/tf-encrypted#311]
Former is [deprecated per 20/8](https://www.tensorflow.org/api_docs/python/tf/Print)!

Closed by #348

**Comment by bendecoste** [comment]
This poses a bit of an issue. `tf.print` doesn't exist in tf 1.9 which we claim support for.  On the other end of the spectrum I believe `tf.Print` will be gone next release which we will definitely want to support.

We could get sophisticated and use a specific one depending on version.  Or we could drop support for tf 1.9.

This also has loose ties to #345 .

**Comment by jvmancuso** [comment]
I say goodbye to 1.9 -- we'll always remember it, but times are changin'

**Comment by mortendahl** [comment]
yeah, debian 9 seems to pull tf 1.12 so dropping tf 1.9, or even everything before 1.12, works for me

**Comment by justin1121** [comment]
We only support 1.12 now!

**Comment by mortendahl** [comment]
closes with https://github.com/mortendahl/tf-encrypted/pull/348?

**Comment by bendecoste** [comment]
Yes
