### ISSUE TITLE
CI testing for int64

### ISSUE THREAD

**Issue by justin1121** [mortendahl/tf-encrypted#320]
Right now we're not continuously integrating tests with int64 support. We should enable this so we don't get surprising bugs when doing a release!

**Comment by ianlivingstone** [comment]
Just to clarify, are we testing against the int64 build today in CI?

**Comment by justin1121** [comment]
Sorry! Typo we're not continuously integrated with int64 support. Edited above.

**Comment by justin1121** [comment]
This is being done now with the adoption of tensorflow 1.13.1
