### ISSUE TITLE
argmax tests are disabled

### ISSUE THREAD

**Issue by justin1121** [mortendahl/tf-encrypted#329]
SecureNN argmax tests are disabled because they fail to run on circleci because of memory issues. This can be resolved by figuring a way to upgrade circleci or figuring out if there is an underlying problem with the argmax tests causing them to run out of memory.

**Comment by mortendahl** [comment]
They now run for int64, maybe that's good enough for now..?

**Comment by justin1121** [comment]
We aren't running int64 tests as of now! https://github.com/mortendahl/tf-encrypted/issues/320

**Comment by mortendahl** [comment]
Closing this issue as it'll be fixed with #320
