### ISSUE TITLE
Allow TFE to run without first building custom ops?

### ISSUE THREAD

**Issue by mortendahl** [mortendahl/tf-encrypted#334]
Instead of panicking if the custom ops are not available we could raise a warning (or even non-fatal error) and either reduce functionality or fall back to TF's implementation. This might give better experience than being force to compile first.

Depends on #333.

**Comment by ianlivingstone** [comment]
This is a good idea, but if we didn't panic and fell back to TF's implementation it'd mean we're not secure by default.

**Comment by mortendahl** [comment]
I suggest we print a (standard formatted) warning! Maybe even panic if using RemoteConfig.

**Comment by bendecoste** [comment]
Yes it could be a first line kind of thing. Similar to how TF always warns you that you might have built it wrong.

**Comment by mortendahl** [comment]
suggested things to do:
[ ] introduce logger package
[ ] add conditional logic around custom ops
[ ] print warning if custom ops are not used
[ ] print info with suggestions when int100 is used instead of int64
