### ISSUE TITLE
Add Intel MKL support to Docker container

### ISSUE THREAD

**Issue by ianlivingstone** [mortendahl/tf-encrypted#342]
Today, in our benchmarking we're not using Intel MKL or a CPU-optimized version of TensorFlow inside of our docker container. Updating our container to take advantage of these optimizations should provide significant improvements to our runtimes.

Example of how tensorflow builds an MKL optimized container: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.mkl

**Comment by justin1121** [comment]
MKL doesn't support int32 or int64 matmul. So not sure this is worth doing. Closing!

**Comment by mortendahl** [comment]
thanks for looking into it!
