### ISSUE TITLE
Garbled circuit investigation

### ISSUE THREAD

**Issue by justin1121** [mortendahl/tf-encrypted#346]
Garbled circuit is an important tool in the multi-party computation researchers toolkit. It allows any function to computed in an encrypted setting. We want to start investigating deeper into how these could be integrated into tf-encrypted. 

We know we can hook into a established garbled circuit library to take advantage of the circuit compilation and the protocol (including oblivious transfer). But there are a few open questions:

1. Vectorization of the input to the circuit and output to the circuit.
2. Is it feasible to send large binary data (the circuit) using the tensorflow distributed computing interface? Can we just store binary data in a tensor? Related issue (https://github.com/mortendahl/tf-encrypted/issues/66).
3. Point the garbled circuit protocol to use the gRPC connections already established between the tensorflow cluster.

As a first step it would be very valuable to dig deep into some of the existing garbled circuit frameworks:

https://github.com/spaceships/fancy-garbling
https://github.com/encryptogroup/ABY
https://github.com/samee/obliv-c

**Comment by mortendahl** [comment]
FYI several people at the PPML workshop seemed to prefer this one https://github.com/emp-toolkit over ABY and OblivC (waiting for confirmation)

**Comment by justin1121** [comment]
Finished up the investigation into the different frameworks listed here. Basic findings were that it would be pretty difficult to integrate any of these frameworks into tf-encrypted/tensorflow as custom operations. emp-toolkit was definitely the winner here. It appeared to be the fastest plus provide the most flexible API and simplest implementation. fancy-garbled might provide some benefits in the future but it is still quite new and actively being developed for building something with that right now would not be feasible.

Another route to go with this is implementing a garbling circuit framework from scratch. This might be the best way to tackle this as integrating/maintaining one of the frameworks might be just as much work.

All in all integrating garbling circuits would be big task that would take quite a bit of planning. If there is any interest feel free to contact me with questions!

**Comment by mortendahl** [comment]
Closing issue
