### ISSUE TITLE
Building custom ops that use Shard on debian stretch seg faults when used

### ISSUE THREAD

**Issue by justin1121** [mortendahl/tf-encrypted#349]
When building custom ops that use Shard (the recommended function to enable parallelism in custom ops) on debian stretch and then executing the op causes a seg fault to occur. This is related to the version of g++ thats in the package repo for debian stretch. This effects running the secure random_uniform op concurrently!

Related issue: https://github.com/tensorflow/tensorflow/issues/13308.

Debian Stretch g++ Version:  6.3.0
Debian Jessie g++ Version: 4.9.2
Ubuntu 18.04 g++ Version: 7.3.0

Seems to be a specific problem when building custom ops with g++ versions 5 and 6 and probably related to ABI compatibility features in g++. Official tensorflow packages are always built with 4.9.0! This shouldn't effect our pip distributions on machines with g++ 5 or 6, as long as they are built with versions 4 or 7!

**Comment by ianlivingstone** [comment]
Can we just upgrade the version of g++?

**Comment by mortendahl** [comment]
tested this as part of https://github.com/mortendahl/tf-encrypted/pull/386 but didn't notice any issues. any particular circumstances under which you ran into this?

fyi it looked like TF (version 1.12) added the required ABI flag on its own.

**Comment by justin1121** [comment]
Looked like @mortendahl observation came from a different between the secure_random operation and the seeded version. Secure random currently uses the `Shard` function whereas the seeded version doesn't per https://github.com/mortendahl/tf-encrypted/issues/270. Currently waiting for PR https://github.com/mortendahl/tf-encrypted/pull/386 which contains documentation on how to build with docker which fixes this issue!

**Comment by justin1121** [comment]
This can be closed! Fixed with documentation!
