### ISSUE TITLE
int100tensor does not have the attribute "value"

### ISSUE THREAD

**Issue by vishwajit123** [mortendahl/tf-encrypted#355]
Currently requires a specific tf build which enables int64tensors to use the value attribute (used in helper functions)

**Comment by justin1121** [comment]
This happens in the debug helper function in pond right?

**Comment by mortendahl** [comment]
Hi @vishwajit123, `value` is supposed to be a private field so it's on purpose that `int100` doesn't have it! Do you need it for a specific reason?

**Comment by vishwajit123** [comment]
@justin1121  Yeah
@mortendahl Needed it to access the values of shares. Yeah that makes sense

**Comment by justin1121** [comment]
Yeah I think the main problem here is that the debug function is trying to access the `.value` attribute. So this helper debug function will only work Int64Tensors since the Int100Tensors don't have this attribute!

**Comment by jvmancuso** [comment]
this may not be the best way forward, but I feel like you could create a property on Int100Tensor called `value` that reconstructs a truncated version of the Int100Tensor from the CRT decomposition.  The property would make it lazy, so you wouldn't be doing it every time you initialize an Int100, but it'd still work with this function

alternatively, we could reserve a special hidden attribute/property for each tensor that works with debugging statements like this

**Comment by vishwajit123** [comment]
@jvmancuso  reconstructing the int100Tensor from crt decomposition makes sense. But I believe reserving a specific attribute only for debugging (for all tensor types) would make things easier.

**Comment by jvmancuso** [comment]
I suggest we standardize it as a property across all dtype tensors and call it something like `_debug_value`.  For Int64Tensor, it can simply retrieve the `value` attribute.

Any takers for a PR? 😄

**Comment by justin1121** [comment]
Related https://github.com/mortendahl/tf-encrypted/issues/278

**Comment by mortendahl** [comment]
@jvmancuso what type would you reconstruct into (it has to hold 100 bits)? There is a `to_native` that's converting to int32 already but that was intended more for working with fixedpoint representation.

**Comment by vishwajit123** [comment]
@mortendahl  I think to_native should be enough
I added this method to send the tensor to whichever party (mostly used prediction client ) that wants to debug. Does this make sense?
```
def send_share( 
        self,
        player: Union[str, Player],
        xs: Union['PondPrivateTensor', List['PondPrivateTensor']],
        outputter_fn: Callable[..., Any],
        name: Optional[str]=None
    ) -> tf.Operation:

        if isinstance(player, str):
            player = get_config().get_player(player)
        assert isinstance(player, Player)

       #send only the first slice of first share

        def helper(x: Union['PondPrivateTensor', 'PondMaskedTensor']) -> tf.Tensor:
            return x.share0.__getitem__(slice=0).to_native() 

        with tf.name_scope('print-output{}'.format('-' + name if name else '')):

            with tf.device(player.device_name):

                if isinstance(xs, (list, tuple)):
                    op = outputter_fn(*[helper(x) for x in xs])

                else:
                    op = outputter_fn(helper(xs))

                op = tf.group(op)

        return op
```

**Comment by mortendahl** [comment]
Hi @vishwajit123, it's not entirely clear to me what we're aiming for here - do you have an example script where you'd like to use this?

One comment is that unless you're using a `RemoteConfig` then it shouldn't matter where the value is reconstructed as all players will print to the same screen. Another is that calling `to_native()` on a share is tricky as it'll squeeze a 100 bit value into a 32 bit value, which might be throwing away too much information wrt shares.

**Comment by vishwajit123** [comment]
Yeah, makes sense. Not using this (was originally written so any pred-client can receive and view the share).
