### ISSUE TITLE
More aggressive use of seeds

### ISSUE THREAD

**Issue by mortendahl** [mortendahl/tf-encrypted#366]
use seeded tensors where possible in SecureNN:
 - [x] int64
 - [x] int32
 - [x] odd
 - [x] prime
 - [x] int100

Child of #364

**Comment by kamathhrishi** [comment]
Could you elaborate a little more on the issue?

**Comment by mortendahl** [comment]
sure! the overall plan is to avoid sending large random tensors whenever possible and instead send small seeds for a pseudo-random generator. this is a typical space/time trade-off (communication vs computation) but so far it has only been partially implemented due to lack of support in tensorflow. however, we now have an operation for generating and expanding seeds, and simply need to build it into our tensor types.
