### ISSUE TITLE
Running instructions for multiple machines (non cloud based)

### ISSUE THREAD

**Issue by innerop** [mortendahl/tf-encrypted#373]
Hi,

I can understand why you use GCP in the instructions since not many people have multiple machines and VMs are not desired for performance reasons. However, there are those of us who would like to try it on multiple machines outside the cloud environment on bare metal servers. 

Any chance you could amend the instructions o include such scenario?

Thanks,

**Comment by mortendahl** [comment]
Hi @innerop, thanks for reaching out! I'll try to put a guide together in the coming days; any particular platform/stack you're most interested in using?

**Comment by mortendahl** [comment]
Hi @innerop, finally got around to writing a text for this: https://github.com/mortendahl/tf-encrypted/blob/master/docs/RUNNING.md. Any feedback is appreciated.
