### ISSUE TITLE
`Make clean` does not remove compiled custom ops

### ISSUE THREAD

**Issue by mortendahl** [mortendahl/tf-encrypted#385]
Is it better to move all of them to the `build` directory instead of inline with the source code?

**Comment by justin1121** [comment]
I think this is just a bug in the makefile. It looks like tensorflow recommends putting the shared objects inline with the source code here https://github.com/tensorflow/custom-op/blob/master/tensorflow_zero_out/BUILD#L6. Might be worth switching to bazel soon and copying their recommended layout as well. python/ops/..., cc/kernels/..., cc/ops/...

**Comment by justin1121** [comment]
I think you can just do `rm tf_encrypted/operations/*.so`

**Comment by justin1121** [comment]
But if you're thinking for future operations `find` makes sense too!

**Comment by mortendahl** [comment]
It was to be less specific yes!
