### ISSUE TITLE
Tensorflow 2.0 support

### ISSUE THREAD

**Issue by bendecoste** [mortendahl/tf-encrypted#388]
This issue encompasses all the exploration required to ensure we can say that tensorflow 2.0 is supported.

There is a good overview covering what is new [written by the tensorflow team](https://medium.com/tensorflow/whats-coming-in-tensorflow-2-0-d3663832e9b8)

I think the 2.0 priorities are

- [ ] eager + `tf.function` (#279)
- [ ] support SavedModel (#54)
- [ ] tighter integration with the keras & estimators APIs
  - will need a sub issue for this once someone takes it on 
- [ ] explore the [`distribution strategy api`](https://www.tensorflow.org/guide/distribute_strategy)
  - may be some MPC benefits here
- [ ] explore tf.data
  - queue runners are being removed in favour of `tf.data`, and `tf.data` is now the preferred way to deal with data, is there anything here we can do to provide a tighter integration with tensorflow.

**Comment by bendecoste** [comment]
@justin1121 @mortendahl @jvmancuso Is there anything else you believe we should investigate?

I think getting a nightly and trying to integrate with the eager stuff would be a good place for us to start.

**Comment by yanndupis** [comment]
Just a quick note, when we [export a model](https://github.com/tensorflow/tensor2tensor/tree/master/tensor2tensor/serving) with Tensor2Tensor, it generates a SavedModel format. We froze this model into a pb file using this [utils](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py).

**Comment by bendecoste** [comment]
This has been investigated and determined that 2.0 should not be a major obstacle.

It is possible to support eager by using the new config api and things basically "just work".

`tf.function` is a bit trickier but can be solved by either api design (e.g. regular tensors go in and out to tfe `tf.function` annotated calls.

SavedModel is not a risk.  It's just a different format we can easily implement.

I'll let @mortendahl update his side of the investigation but those were also non issues.

**Comment by ianlivingstone** [comment]
Should we keep this issue open to track the implementation or open a new one to actually add support for 2.0?

**Comment by bendecoste** [comment]
It's unclear when we would actually do that, plus the issue was exploratory from the start so I recommend opening a new one when the time comes.
