### ISSUE TITLE
Consistent filenames

### ISSUE THREAD

**Issue by bendecoste** [mortendahl/tf-encrypted#391]
Some of the files in this repo use dashes (`-`) and some use underscores (`_`), we should use the same each time imo

e.g. 

```
examples/mnist_deep_cnn.py
examples/securenn-playground.py
examples/federated-average/
examples/house_credit_default/
tf_encrypted/
```

**Comment by mortendahl** [comment]
I can address this in https://github.com/mortendahl/tf-encrypted/pull/379
