### ISSUE TITLE
layers.Conv2D.initialize() doesn't accept bias as a parameter

### ISSUE THREAD

**Issue by tshead2** [mortendahl/tf-encrypted#396]
Like it says, the current API always initializes the bias to zero.  This is a problem when trying to load a pre-trained model.  Weirdly, assigning to the bias attribute after calling initialize() led to strange errors (apologies for not writing them down).

**Comment by justin1121** [comment]
Hey Tim,

I've fixed this issue in this PR https://github.com/mortendahl/tf-encrypted/pull/398.

May I also suggest taking a look at the converter in the convert directory. You can use this if you have an already trained model in the tensorflow GraphDef format. You can see some examples in the `tests/test_convert.py` file or even the `bin/run` file. Let me know if you have any questions. Thanks!

Justin
