### ISSUE TITLE
int64 native support in TF

### ISSUE THREAD

**Issue by bendecoste** [mortendahl/tf-encrypted#79]
Using int64 natively in TF, would allow to gain substantial speed up by leveraging the ring it creates.

We need to investigate how much work should be done to use int64 operations in TF.

related https://github.com/tensorflow/tensorflow/pull/21253

**Comment by justin1121** [comment]
I've built a tensorflow pip package based on the branch linked above and doing a simple matmul works so far. If anyone wants the pip package I can. Only think it'll work on macos though.

**Comment by ianlivingstone** [comment]
We want to land optional int64 support in master behind an optional tensor type. They will need to install and use our optional built version of TensorFlow w/ int64 support.

**Comment by mortendahl** [comment]
@justin1121 nice, i'd like to give it a try!

**Comment by justin1121** [comment]
Above tensorflow PR has been approved. Just waiting on merging and release!

**Comment by ianlivingstone** [comment]
Was this included in https://github.com/tensorflow/tensorflow/releases/tag/v1.11.0 ?

**Comment by justin1121** [comment]
No. Still waiting for this to be merged internally by Google.
