### ISSUE TITLE
rename 'master' node

### ISSUE THREAD

**Issue by bendecoste** [mortendahl/tf-encrypted#83]
We should consider renaming the 'master' node to 'api' or similar to avoid the master/slave dichotomy that is now considered politically incorrect.

**Comment by mortendahl** [comment]
`master` is technical terminology in TensorFlow: https://www.tensorflow.org/deploy/distributed

**Comment by justin1121** [comment]
Yeah I agree if tensorflow uses "master" we should probably stick with that. Maybe avoid slave?

**Comment by ianlivingstone** [comment]
Let's stick with "master" and if it comes up again we can re-open and reconsider, alignment with TF terminology is golden!
