### ISSUE TITLE
improve linting

### ISSUE THREAD

**Issue by bendecoste** [mortendahl/tf-encrypted#84]
We have currently satisfied the `pycodestyle` linter but we would like to check for more different errors.
so we are adding `pyflakes`.

Many other tools could also be used like `flake8` or `pylint`.

It would be interesting to know if those tools are complementary or redundant. 
My current understanding is
- `pyflakes` and `flake8` are redundant but they are complementary with `pycodestyle` and `pylint` .
- `pylint` seems very pedantic and might be too much for a linter

**Comment by ianlivingstone** [comment]
@morgangiraud is this still relevant? I know you did some work here not so long ago!

**Comment by morgangiraud** [comment]
No, it's not, I think we have enough linting for now.

We can close it.
