### ISSUE TITLE
Compiling graphs

### ISSUE THREAD

**Issue by mortendahl** [mortendahl/tf-encrypted#85]
Look into whether this gives any significant performance boosts:
- https://www.tensorflow.org/performance/xla/tfcompile
- https://www.tensorflow.org/xla/tutorials/xla_compile

**Comment by mortendahl** [comment]
this might be an issue: "the resulting pruned subgraph cannot contain Placeholder or Variable nodes"

**Comment by morgangiraud** [comment]
`tfcompile` is made to be used for inference purpose, so as long as we can freeze a graph to remove variables, we're fine with the Variable limitation.

About the placeholders, I guess you can always `tfcompile` from  the first operation after placeholders  , no?

**Comment by mortendahl** [comment]
I think you can still have placeholders in the compiled graph, no?

**Comment by mortendahl** [comment]
next step could be to simply get a compiled version of TensorFlow with XLA support running

**Comment by justin1121** [comment]
Further investigation has gone into using XLA to compile graphs and doesn't really seem beneficial at this point.

**Comment by justin1121** [comment]
See this comment https://github.com/mortendahl/tf-encrypted/issues/229#issuecomment-462420840.
